import = [
    "~/.config/alacritty/themes/themes/dracula.toml"
]
	
[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "None"

opacity = 1.0
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 18

